### ISSUE TITLE
Api - Check course is in mamber

### ISSUE THREAD

**Issue by vikriyuwi** [latifulfikri/website_becademy#5]
Contoller : **ApiCourseController**
Route : **"course/slug/is-member" [get]**

Response : {
>"status":200
>"message":"True"
>"data": [
>>"result":true

>]
  
>"status":200
>"message":"False"
>"data": [
>>"result":true

>]

}

Description:
Buat cek user yg login ini member sebuah course apa bukan

Note:
Buat get data user login => Auth::guard('api')->user()
Pake template response (new ApiResponse)

**Comment by thalentadeha** [comment]
done
