### ISSUE TITLE
Api - View all member payment

### ISSUE THREAD

**Issue by vikriyuwi** [latifulfikri/website_becademy#6]
Contoller : **ApiMemberController** (buat baru kl belum ada)
Route : **"/member" [get]**
(id -. id di tabel member)

Description:
Buat liat semua data member payment
(semua data di tabel member)

Note:
Cuma bisa diakses admin, jadi routenya tulis di yang ada middleware('apiAdmin')
Jgn lupa pass query pake **with('Course')**.. misal MemberMode::**with('Course')**->where()....

**Comment by thalentadeha** [comment]
done
