### ISSUE TITLE
Api - View a data member payment

### ISSUE THREAD

**Issue by vikriyuwi** [latifulfikri/website_becademy#7]
Contoller : **ApiMemberController** (buat baru kl belum ada)
Route : **"member/{id}/detail" [get]**
(id -. id di tabel member)

Description:
Buat liat data payment masing2 data

Note:
Cuma bisa diakses admin, jadi routenya tulis di yang ada middleware('apiAdmin')
Jgn lupa pass query pake **with('Course')**.. misal MemberMode::**with('Course')**->where()....

**Comment by thalentadeha** [comment]
done
