### ISSUE TITLE
Api - Member payment verified by admin

### ISSUE THREAD

**Issue by vikriyuwi** [latifulfikri/website_becademy#8]
Contoller : **ApiMemberController**
Route : **"member/{id}/payment/verify" [get]**
(id -. id di tabel member)

Description:
Buat nge-verify payment member isi pake integer
Jadi nanti pas verify nya bisa update jadi 1 atau 2, kaya update data biasa

- 0 : process / new
- 1 : success
- 2 : fail

Note:
Karena yang verify itu cuma bisa admin, jadi routenya tulis di yang ada middleware('apiAdmin')

**Comment by thalentadeha** [comment]
done
